name: flutter_storyblok_code_generator
description: Code generator for flutter_storyblok
version: 1.0.0
homepage: https://www.alster.se/
repository: https://github.com/alsterverse/flutter_storyblok
issue_tracker: https://github.com/alsterverse/flutter_storyblok/issues
topics:
  - storyblok
  - sdk

executables:
  codegen: main

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
      sdk: flutter
  flutter_storyblok: any
  dart_style: any
  code_builder: ^4.10.0
  dart_casing: ^3.0.1
  http: ^1.2.1
  collection: ^1.18.0
  characters: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

dependency_overrides:
  code_builder: # Until fork gets merged
    git:
      url: https://github.com/PhiFry/code_builder
      ref: 59f7ceb9a61389debab0755a6147c85f360640a6
