name: flutter_storyblok
description: A new Flutter package project.
version: 0.0.1+1

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

dependency_overrides:
  code_builder: # Until fork gets merged
    git:
      url: https://github.com/PhiFry/code_builder
      ref: 59f7ceb9a61389debab0755a6147c85f360640a6
